In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['01-0235'],
    
    'AD ITEM NUMBER': ['140316'],
    
    'Vendor Notes': ['CR PRO'],
}

#List of Models

list_models = [
    'TRX350',
    'TRX350D'

]

#Range of years
years = list(range( 1986, 1990))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\1.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['01-0609'],
    
    'AD ITEM NUMBER': ['140536'],
    
    'Vendor Notes': ['CR PRO'],
}

#List of Models

list_models = [
   ' TRX350FE FourTrax Rancher 4x4 ES',
'TRX350FM FourTrax Rancher 4X4',
'TRX350TE FourTrax Rancher ES',
'TRX350TM FourTrax Rancher'

]

#Range of years
years = list(range( 2000, 2007))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\2.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['01-1056'],
    
    'AD ITEM NUMBER': ['140736'],
    
    'Vendor Notes': ['CR PRO'],
}

#List of Models

list_models = [
   'Sportsman 450 HO',
    'Outlaw 525 IRS',
    'Outlaw 525 S'


]

#Range of years
years = list(range( 2007, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\3.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['01-1056'],
    
    'AD ITEM NUMBER': ['140736'],
    
    'Vendor Notes': ['CR COMP'],
}

#List of Models

list_models = [
   'Sportsman 450 HO',
    'Outlaw 525 IRS',
    'Outlaw 525 S'


]

#Range of years
years = list(range( 2007, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\4.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['02-0138'],
    
    'AD ITEM NUMBER': ['672138'],
    
    'Vendor Notes': ['CR PRO'],
}

#List of Models

list_models = [
   'ATC250R'



]

#Range of years
years = list(range( 1981, 1985))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\5.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['101-1153'],
    
    'AD ITEM NUMBER': ['127672'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
   'Thundercat 1000 4x4 Auto',
'Thundercat 1000 4x4 Auto LE',
'TRV 1000i Cruiser',
'TRV 1000i GT',
'1000i GT',
'TRV 1000 LTD'

]

#Range of years
years = list(range( 2008, 2013))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\6.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['101-1176'],
    
    'AD ITEM NUMBER': ['127701'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'Outlaw 50',
'Outlaw 450 MXR',
'Outlaw 525 S',
'Outlaw 525 IRS'


]

#Range of years
years = list(range( 2009, 2012))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\7.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['101-1200'],
    
    'AD ITEM NUMBER': ['127669'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'550 TRV Cruiser',
'550 TRV GT',
'550 LTD',
'550 4x4 Auto',
'TRV 550i GT',
'550i LTD',
'550i GT',
'550',
'TRV 550 LTD',
'TRV 550 XT'


]

#Range of years
years = list(range( 2011, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\8.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['101-1200'],
    
    'AD ITEM NUMBER': ['127669'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'700 EFI 4x4 Auto TRV Cruiser',
'700 TRV GT',
'700 EFI H1 4x4 Auto TRV',
'700 LTD',
'700 EFI H1 4x4 Auto Mud Pro',
'TBX 700 LTD',
'TRV 700i GT',
'TRV 700i Cruiser',
'700i LTD',
'700i GT',
'700i',
'TBX 700i GT',
'700 XT',
'TRV 700 LTD',
'TRV 700 XT',
'TBX 700 XT',
'TBX 700'
'TRV 550 XT'


]

#Range of years
years = list(range( 2011, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\9.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['101-409'],
    
    'AD ITEM NUMBER': ['126705'],
    
    'Vendor Notes': ['TURBO'],
}

#List of Models

list_models = [
    
'ATC250R'

]

#Range of years
years = list(range( 1985, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\10.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-024**'],
    
    'AD ITEM NUMBER': ['122206'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC185',
'ATC185S',
'ATC200'


]

#Range of years
years = list(range( 1980, 1984))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\11.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-025*'],
    
    'AD ITEM NUMBER': ['122207'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC185',
'ATC185S',
'ATC200'


]

#Range of years
years = list(range( 1980, 1983))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\12.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-036'],
    
    'AD ITEM NUMBER': ['126745'],
    
    'Vendor Notes': ['CR COMP'],
}

#List of Models

list_models = [
    
'LT80 QuadSport',
'YFS200 Blaster'



]

#Range of years
years = list(range( 1987, 2007))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\13.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-046'],
    
    'AD ITEM NUMBER': ['122205'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC185',
'ATC185S',
'ATC200'




]

#Range of years
years = list(range( 1980, 1985))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\14.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-048'],
    
    'AD ITEM NUMBER': ['122218'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC250R'





]

#Range of years
years = list(range( 1981, 1983))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\15.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-054'],
    
    'AD ITEM NUMBER': ['122214'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC200'


]

#Range of years
years = list(range( 1985, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\16.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-055'],
    
    'AD ITEM NUMBER': ['122215'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'ATC200X'


]

#Range of years
years = list(range( 1983, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\17.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-056**'],
    
    'AD ITEM NUMBER': ['122216'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC200X',
'ATC350X'



]

#Range of years
years = list(range( 1983, 1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\18.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-060'],
    
    'AD ITEM NUMBER': ['122219'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'ATC250R'



]

#Range of years
years = list(range( 1981, 1985))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\19.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-062'],
    
    'AD ITEM NUMBER': ['122220'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC250R'



]

#Range of years
years = list(range( 1983, 1985))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\20.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-074'],
    
    'AD ITEM NUMBER': ['122217'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'ATC200X'



]

#Range of years
years = list(range( 1986, 1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\21.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-077'],
    
    'AD ITEM NUMBER': ['127684'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC110',
'ATC125M'  




]

#Range of years
years = list(range( 1984, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\22.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-080*'],
    
    'AD ITEM NUMBER': ['127763'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC125M'  




]

#Range of years
years = list(range( 1986, 1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\23.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-081'],
    
    'AD ITEM NUMBER': ['127762'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC110',
'TRX125'

]

#Range of years
years = list(range( 1984, 1987))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\24.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-082***'],
    
    'AD ITEM NUMBER': ['127762'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC185',
'ATC185S',
'ATC200'


]

#Range of years
years = list(range( 1980, 1985))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\25.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-091*'],
    
    'AD ITEM NUMBER': ['122209'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC185',
'ATC185S',
'ATC200'


]

#Range of years
years = list(range( 1983, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\26.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-092**'],
    
    'AD ITEM NUMBER': ['122204'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC200ES',
'ATC200M',
'ATC200S',
'ATC200X',
'TRX200SX',
'TRX200'


]

#Range of years
years = list(range( 1984, 1989))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\27.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-135'],
    
    'AD ITEM NUMBER': ['122222'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC250ES Big Red',
'ATC250R',
'ATC250SX',
'TRX250',
'ATC350X',
'TRX350',
'TRX350D'


]

#Range of years
years = list(range( 1985, 2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\28.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-141**'],
    
    'AD ITEM NUMBER': ['122210'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'ATC250ES Big Red',
'TRX200SX',
'TRX200',
'TRX250',
'TRX250R'


]

#Range of years
years = list(range( 1985, 1992))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\29.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-142'],
    
    'AD ITEM NUMBER': ['127755'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'Outlander 650 EFI',
'Outlander 650 EFI DPS',
'Outlander 650',
'Outlander 650 DPS',
'Outlander 570 DPS',
'Outlander 570',
'Outlander Max 400 EFI XT',
'Outlander Max 400 EFI',
'Outlander Max 450',
'Outlander Max 450 DPS',
'ATC125M',
'ATC250ES Big Red',
'ATC250R',
'ATC250SX',
'TRX200 FourTrax',
'TRX200D FourTrax Type II',
'TRX200SX',
'TRX200'


]

#Range of years
years = list(range(1985, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\30.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-144'],
    
    'AD ITEM NUMBER': ['122233'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'ATC350X'



]

#Range of years
years = list(range(1985, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\31.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-149'],
    
    'AD ITEM NUMBER': ['122213'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'ATC200'



]

#Range of years
years = list(range(1981, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\32.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-157'],
    
    'AD ITEM NUMBER': ['127749'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX200SX'



]

#Range of years
years = list(range(1997, 2002))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\33.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-179'],
    
    'AD ITEM NUMBER': ['122237'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX350',
'TRX350D'



]

#Range of years
years = list(range(1997, 2002))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\34.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-181***'],
    
    'AD ITEM NUMBER': ['127765'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX200SX'



]

#Range of years
years = list(range(1997, 2002))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\35.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-184'],
    
    'AD ITEM NUMBER': ['122223'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC250ES Big Red',
'TRX250'



]

#Range of years
years = list(range(1986, 1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\36.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-185'],
    
    'AD ITEM NUMBER': ['122203'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'ATC70'




]

#Range of years
years = list(range(1978, 1986))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\37.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-201'],
    
    'AD ITEM NUMBER': ['126716'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'KLF400 Bayou 4x4',
 'KVF400 Prairie 2x4',
'KVF400 Prairie 4x4'
   





]

#Range of years
years = list(range(1993, 2002))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\38.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-202'],
    
    'AD ITEM NUMBER': ['122212'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX200SX',
'TRX250',
'TRX250EX Sportrax',
'TRX250TE FourTrax Recon ES',
'TRX250TM FourTrax Recon',
'TRX250X'
   
]

#Range of years
years = list(range(1997, 2006))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\39.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-214'],
    
    'AD ITEM NUMBER': ['122234'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'ATC350X'

   
]

#Range of years
years = list(range(1986, 1987))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\40.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-247'],
    
    'AD ITEM NUMBER': ['126679'],
    
    'Vendor Notes': ['CR PRO'],
}

#List of Models

list_models = [
    
'ATC250R',
'LT250R QuadRacer'

   
]

#Range of years
years = list(range(1985, 1993))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\41.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-247'],
    
    'AD ITEM NUMBER': ['126679'],
    
    'Vendor Notes': ['CR COMP'],
}

#List of Models

list_models = [
    
'LT250R QuadRacer'

   
]

#Range of years
years = list(range(1987, 1993))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\42.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-254'],
    
    'AD ITEM NUMBER': ['122211'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX200D FourTrax Type II',
'TRX200'

   
]

#Range of years
years = list(range(1990, 1998))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\43.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-282'],
    
    'AD ITEM NUMBER': ['122227'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'


   
]

#Range of years
years = list(range(1988, 2001))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\44.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-288**'],
    
    'AD ITEM NUMBER': ['122229'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'
   
]

#Range of years
years = list(range(1988, 1996))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\45.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-289'],
    
    'AD ITEM NUMBER': ['122230'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'
   
]

#Range of years
years = list(range(1988, 1996))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\46.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-355**'],
    
    'AD ITEM NUMBER': ['122236'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX400FGA FourTrax Rancher AT GPScape',
'TRX400FW Foreman 4x4',
'TRX500FA FourTrax Foreman Rubicon',
'TRX500FGA FourTrax Foreman Rubicon GPScape',
'TRX500FE FourTrax Foreman 4x4 ES',
'TRX500FM FourTrax Foreman 4x4',
'TRX500FPE FourTrax Foreman 4x4 ES w/Power Steering',
'TRX500FPM FourTrax Foreman 4x4 w/ Power Steering',
'TRX500TM FourTrax Foreman',
'TRX500FPA FourTrax Foreman Rubicon with EPS',
'TRX500FM1 FourTrax Foreman 4x4',
'TRX500FE1 FourTrax Foreman 4x4 ES',
'TRX500FM2 FourTrax Foreman 4x4 with EPS',
'TRX500FE2 FourTrax Foreman 4x4 ES with EPS',
'TRX500FM5 FourTrax Foreman Rubicon',
'TRX500FM6 FourTrax Foreman Rubicon EPS',
'TRX500FM6D FourTrax Foreman Rubicon EPS DLX',
'TRX500FA5 FourTrax Foreman Rubicon Auto DCT',
'TRX500FA6 FourTrax Foreman Rubicon Auto DCT EPS',
'TRX500FA6D FourTrax Foreman Rubicon Auto DCT EPS D',
'TRX500FA7 FourTrax Foreman Rubicon Auto DCT EPS DL',
'TRX500FM7 FourTrax Foreman Rubicon EPS DLX',
'TRX400FA FourTrax Rancher AT'

   
]

#Range of years
years = list(range(1995, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\47.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-357'],
    
    'AD ITEM NUMBER': ['127767'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'


   
]

#Range of years
years = list(range(1996, 2001))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\48.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-359'],
    
    'AD ITEM NUMBER': ['122231'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'


   
]

#Range of years
years = list(range(1996, 2001))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\49.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-361'],
    
    'AD ITEM NUMBER': ['122228'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'TRX300 FourTrax',
'TRX300FW FourTrax 4x4'


   
]

#Range of years
years = list(range(1988, 2001))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\50.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-375'],
    
    'AD ITEM NUMBER': ['122235'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX350FE FourTrax Rancher 4x4 ES',
'TRX350FM FourTrax Rancher 4X4',
'TRX350TE FourTrax Rancher ES',
'TRX350TM FourTrax Rancher',
'TRX400FA FourTrax Rancher AT',
'TRX400FGA FourTrax Rancher AT GPScape',
'TRX400FW Foreman 4x4',
'TRX420FE FourTrax Rancher 4X4 ES',
'TRX420FM FourTrax Rancher 4X4',
'TRX420TE FourTrax Rancher ES',
'TRX420TM FourTrax Rancher',
'TRX420FPA Rancher AT 4x4 w/ Power Steering',
'TRX420FPE Rancher ES 4x4 w/ Power Steering',
'TRX420FPM Rancher 4x4 w/ Power Steering',
'TRX420FA Rancher AT',
'TRX420TM1 FourTrax Rancher',
'TRX420TE1 FourTrax Rancher ES',
'TRX420FM1 FourTrax Rancher 4x4',
'TRX420FE1 FourTrax Rancher 4x4 ES',
'TRX420FM2 FourTrax Rancher 4x4 with EPS',
'TRX420FA2 FourTrax Rancher 4x4 Auto DCT with EPS',
'TRX420FA1 FourTrax Rancher 4x4 Auto DCT',
'TRX420FA5 FourTrax Rancher 4x4 Auto DCT IRS',
'TRX420FA6 FourTrax Rancher 4x4 Auto DCT IRS EPS',
'TRX450ER Electric Start',
'TRX450FE FourTrax Foreman ES',
'TRX450FM FourTrax Foreman S',
'TRX450R',
'TRX500FA FourTrax Foreman Rubicon',
'TRX500FGA FourTrax Foreman Rubicon GPScape',
'TRX500FE FourTrax Foreman 4x4 ES',
'TRX500FM FourTrax Foreman 4x4',
'TRX500FPE FourTrax Foreman 4x4 ES w/Power Steering',
'TRX500FPM FourTrax Foreman 4x4 w/ Power Steering',
'TRX500TM FourTrax Foreman',
'TRX500FPA FourTrax Foreman Rubicon with EPS',
'TRX500FM1 FourTrax Foreman 4x4',
'TRX500FE1 FourTrax Foreman 4x4 ES',
'TRX500FM2 FourTrax Foreman 4x4 with EPS',
'TRX500FE2 FourTrax Foreman 4x4 ES with EPS',
'TRX500FM5 FourTrax Foreman Rubicon',
'TRX500FM6 FourTrax Foreman Rubicon EPS',
'TRX500FM6D FourTrax Foreman Rubicon EPS DLX',
'TRX500FA5 FourTrax Foreman Rubicon Auto DCT',
'TRX500FA6 FourTrax Foreman Rubicon Auto DCT EPS',
'TRX500FA6D FourTrax Foreman Rubicon Auto DCT EPS D',
'TRX500FA7 FourTrax Foreman Rubicon Auto DCT EPS DL',
'TRX500FM7 FourTrax Foreman Rubicon EPS DLX',
'TRX650FA FourTrax Rincon',
'TRX650FGA FourTrax Rincon GPScape',
'TRX680FA FourTrax Rincon',
'TRX680FGA FourTrax Rincon GPScape'


   
]

#Range of years
years = list(range(1995, 2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\51.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-382'],
    
    'AD ITEM NUMBER': ['122239'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'TRX400EX Sportrax',
'TRX400X'

]
#Range of years
years = list(range(1999, 2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\52.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-385**'],
    
    'AD ITEM NUMBER': ['122224'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TRX250TE FourTrax Recon ES',
'TRX250TM FourTrax Recon',
'TRX250X',
'TRX250X SE'


]
#Range of years
years = list(range(1997, 2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\53.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-405'],
    
    'AD ITEM NUMBER': ['122243'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'TRX450ER Electric Start',
'TRX450R'



]
#Range of years
years = list(range(1997, 2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\54.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-408'],
    
    'AD ITEM NUMBER': ['122242'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX450ER Electric Start',
'TRX450R'



]
#Range of years
years = list(range(2004, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\55.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-409****'],
    
    'AD ITEM NUMBER': ['127794'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX450ER Electric Start',
'TRX450R'



]
#Range of years
years = list(range(2004, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\56.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-410'],
    
    'AD ITEM NUMBER': ['127773'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX450ER Electric Start',
'TRX450R'



]
#Range of years
years = list(range(2004, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\57.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-411'],
    
    'AD ITEM NUMBER': ['127681'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX90EX Sportrax',
'TRX90X'



]
#Range of years
years = list(range(1993, 2023))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\58.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-517'],
    
    'AD ITEM NUMBER': ['122238'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX400EX Sportrax',
'TRX400X'



]
#Range of years
years = list(range(1999, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\59.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-519'],
    
    'AD ITEM NUMBER': ['122244'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX500FA FourTrax Foreman Rubicon',
'TRX500FGA FourTrax Foreman Rubicon GPScape',
'TRX500FE FourTrax Foreman 4x4 ES',
'TRX500FM FourTrax Foreman 4x4',
'TRX500FPE FourTrax Foreman 4x4 ES w/Power Steering',
'TRX500FPM FourTrax Foreman 4x4 w/ Power Steering',
'TRX500TM FourTrax Foreman',
'TRX500FPA FourTrax Foreman Rubicon with EPS',
'TRX500FM1 FourTrax Foreman 4x4',
'TRX500FE1 FourTrax Foreman 4x4 ES',
'TRX500FM2 FourTrax Foreman 4x4 with EPS',
'TRX500FE2 FourTrax Foreman 4x4 ES with EPS',
'TRX500FM5 FourTrax Foreman Rubicon',
'TRX500FM6 FourTrax Foreman Rubicon EPS',
'TRX500FM6D FourTrax Foreman Rubicon EPS DLX',
'TRX500FA5 FourTrax Foreman Rubicon Auto DCT',
'TRX500FA6 FourTrax Foreman Rubicon Auto DCT EPS',
'TRX500FA6D FourTrax Foreman Rubicon Auto DCT EPS D'

]
#Range of years
years = list(range(2004, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\60.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-518'],
    
    'AD ITEM NUMBER': ['122240'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'TRX400EX Sportrax',
'TRX400X'


]
#Range of years
years = list(range(2005, 2008))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\61.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-539'],
    
    'AD ITEM NUMBER': ['127756'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'TRX300EX Sportrax',
'TRX300X'


]
#Range of years
years = list(range(2007, 2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\62.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-539'],
    
    'AD ITEM NUMBER': ['127756'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'TRX650FA FourTrax Rincon',
'TRX650FGA FourTrax Rincon GPScape',
'TRX680FA FourTrax Rincon',
'TRX680FGA FourTrax Rincon GPScape'


]
#Range of years
years = list(range(2003, 2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\63.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-546'],
    
    'AD ITEM NUMBER': ['122225'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TX250X'



]
#Range of years
years = list(range(2006,2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\64.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-547'],
    
    'AD ITEM NUMBER': ['127750'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TRX250X'



]
#Range of years
years = list(range(2006,2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\65.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-548'],
    
    'AD ITEM NUMBER': ['122241'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'TRX400EX Sportrax',
'TRX400X'



]
#Range of years
years = list(range(2008,2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\66.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-558'],
    
    'AD ITEM NUMBER': ['127793'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TRX250TE FourTrax Recon ES',
'TRX250TM FourTrax Recon',
'TRX250X'



]
#Range of years
years = list(range(2006,2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\67.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-559'],
    
    'AD ITEM NUMBER': ['127766'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TRX250TE FourTrax Recon ES',
'TRX250TM FourTrax Recon',
'TRX250X',
'TRX420FE FourTrax Rancher 4X4 ES',
'TRX420FM FourTrax Rancher 4X4',
'TRX420TE FourTrax Rancher ES',
'TRX420TM FourTrax Rancher',
'TRX420FPA Rancher AT 4x4 w/ Power Steering',
'TRX420FPE Rancher ES 4x4 w/ Power Steering',
'TRX420FPM Rancher 4x4 w/ Power Steering',
'TRX420FA Rancher AT'



]
#Range of years
years = list(range(2006,2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\68.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-561'],
    
    'AD ITEM NUMBER': ['122226'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX250EX Sportrax',
'TRX250TE FourTrax Recon ES',
'TRX250TM FourTrax Recon',
'TRX250X'



]
#Range of years
years = list(range(2006,2022))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\69.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-568'],
    
    'AD ITEM NUMBER': ['122246'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'TRX700XX'



]
#Range of years
years = list(range(2008,2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\70.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-575'],
    
    'AD ITEM NUMBER': ['127769'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'TRX400EX Sportrax',
'TRX400X'



]
#Range of years
years = list(range(2008,2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\71.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-583**'],
    
    'AD ITEM NUMBER': ['127770'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'TRX420FA Rancher AT',
'TRX420FA2 FourTrax Rancher 4x4 Auto DCT with EPS',
'TRX420FA1 FourTrax Rancher 4x4 Auto DCT',
'TRX420FA5 FourTrax Rancher 4x4 Auto DCT IRS',
'TRX420FA6 FourTrax Rancher 4x4 Auto DCT IRS EPS',
'TRX420FPA Rancher AT 4x4 w/ Power Steering'



]
#Range of years
years = list(range(2009,2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\72.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['102-585**'],
    
    'AD ITEM NUMBER': ['127772'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'TRX450FE FourTrax Foreman ES'




]
#Range of years
years = list(range(2009,2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\73.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-054'],
    
    'AD ITEM NUMBER': ['127691'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KXT250 Tecate'





]
#Range of years
years = list(range(1984,1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\74.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-055'],
    
    'AD ITEM NUMBER': ['127752'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    

'KXT250 Tecate'





]
#Range of years
years = list(range(1984,1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\75.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-073'],
    
    'AD ITEM NUMBER': ['122248'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    

'KLT200',
'KSF250 Mojave'






]
#Range of years
years = list(range(1987,2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\76.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-134'],
    
    'AD ITEM NUMBER': ['126803'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    

'KXT250 Tecate'







]
#Range of years
years = list(range(1986,1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\77.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-186'],
    
    'AD ITEM NUMBER': ['126671'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KLT185'







]
#Range of years
years = list(range(1986,1989))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\78.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-169'],
    
    'AD ITEM NUMBER': ['122249'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KLF220 Bayou',
'KFX250 Mojave',
'KLF250 Bayou',
'KSF250 Mojave',
'KLF300 Bayou 2x4',
'KLF300 Bayou 4x4'


]
#Range of years
years = list(range(1986,2012))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\79.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-201'],
    
    'AD ITEM NUMBER': ['122254'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KVF300 Prairie 2x4',
'KVF300 Prairie 4x4'



]
#Range of years
years = list(range(1999,2003))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\80.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-195'],
    
    'AD ITEM NUMBER': ['127795'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    

'KLF185 Bayou',
'KLF220 Bayou',
'KLF250 Bayou'




]
#Range of years
years = list(range(1987,2012))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\81.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-194'],
    
    'AD ITEM NUMBER': ['122251'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    

'KLF300 Bayou 2x4',
'KLF300 Bayou 4x4',
'KVF300 Prairie 2x4',
'KVF300 Prairie 4x4',
'KLF400 Bayou 4x4',
'KVF400 Prairie 2x4',
'KVF400 Prairie 4x4'



]
#Range of years
years = list(range(1986,2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\82.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-277**'],
    
    'AD ITEM NUMBER': ['122252'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KLF300 Bayou 2x4',
'KLF300 Bayou 4x4',



]
#Range of years
years = list(range(1986,2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\83.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-278**'],
    
    'AD ITEM NUMBER': ['122253'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KLF300 Bayou 2x4',
'KLF300 Bayou 4x4',



]
#Range of years
years = list(range(1986,2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\84.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-270**'],
    
    'AD ITEM NUMBER': ['122258'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KLF400 Bayou 4x4'




]
#Range of years
years = list(range(1993,2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\85.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-271**'],
    
    'AD ITEM NUMBER': ['122259'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KLF400 Bayou 4x4'




]
#Range of years
years = list(range(1993,2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\86.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-271**'],
    
    'AD ITEM NUMBER': ['122259'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    

'KLF400 Bayou 4x4'




]
#Range of years
years = list(range(1993,2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\87.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-270**'],
    
    'AD ITEM NUMBER': ['122258'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    

'KLF400 Bayou 4x4'




]
#Range of years
years = list(range(1993,2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\88.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-279'],
    
    'AD ITEM NUMBER': ['127775'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KLF220 Bayou',
'KLF250 Bayou'





]
#Range of years
years = list(range(1988,2012))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\89.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-309**'],
    
    'AD ITEM NUMBER': ['127777'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KXT250 Tecate'

]
#Range of years
years = list(range(1986,1988))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\90.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-349'],
    
    'AD ITEM NUMBER': ['127692'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KVF360 Prairie 2x4',
'KVF360 Prairie 4x4'


]
#Range of years
years = list(range(2003,2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\91.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-350'],
    
    'AD ITEM NUMBER': ['122261'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    

'KVF650 Brute Force 4x4',
'KVF650 Brute Force 4x4i',
'KVF650 Prairie 4x4',
'KVF700 Prairie 4x4',
'LT-V700F Twin Peaks 700 4x4'


]
#Range of years
years = list(range(2004,2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\92.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-311**'],
    
    'AD ITEM NUMBER': ['122255'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    

'KVF400 Prairie 2x4',
'KVF400 Prairie 4x4'


]
#Range of years
years = list(range(1997, 2003))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\93.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-311**'],
    
    'AD ITEM NUMBER': ['122255'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    

'KVF300 Brute Force'



]
#Range of years
years = list(range(2012, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\94.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-360***'],
    
    'AD ITEM NUMBER': ['122256'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'KVF650 Brute Force 4x4',
'KVF650 Brute Force 4x4i',

]
#Range of years
years = list(range(2006, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\95.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-360***'],
    
    'AD ITEM NUMBER': ['122256'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'LT-V700F Twin Peaks 700 4x4',
'KVF300 Prairie 2x4',
'KVF300 Prairie 4x4'
]
#Range of years
years = list(range(1999, 2005))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\96.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-361'],
    
    'AD ITEM NUMBER': ['122257'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'LT-V700F Twin Peaks 700 4x4',
'KVF300 Prairie 2x4',
'KVF300 Prairie 4x4',
'KVF360 Prairie 2x4',
'KVF360 Prairie 4x4'

]
#Range of years
years = list(range(1999, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\97.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-361'],
    
    'AD ITEM NUMBER': ['122257'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'KVF650 Brute Force 4x4',
'KVF650 Brute Force 4x4i',
'KVF700 Prairie 4x4'


]
#Range of years
years = list(range(2004, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\98.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-362'],
    
    'AD ITEM NUMBER': ['122262'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'KVF650 Brute Force 4x4',
'KVF650 Brute Force 4x4i',
'KVF750 Brute Force 4x4i',
'KVF750 Brute Force 4x4i EPS',
'KVF750 Brute Force 4x4i EPS Camo'


]
#Range of years
years = list(range(2005, 2014))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\99.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-364'],
    
    'AD ITEM NUMBER': ['127693'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'KVF360 Prairie 2x4',
'KVF360 Prairie 4x4'



]
#Range of years
years = list(range(2003, 2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\100.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-373**'],
    
    'AD ITEM NUMBER': ['122264'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'KVF750 Brute Force 4x4i',
'KVF750 Brute Force 4x4i EPS',
'KVF750 Brute Force 4x4i EPS Camo'



]
#Range of years
years = list(range(2005, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\101.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-372***'],
    
    'AD ITEM NUMBER': ['122265'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'KVF750 Brute Force 4x4i',
'KVF750 Brute Force 4x4i EPS',
'KVF750 Brute Force 4x4i EPS Camo'



]
#Range of years
years = list(range(2005, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\102.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-374'],
    
    'AD ITEM NUMBER': ['127753'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'KFX450R'




]
#Range of years
years = list(range(2008, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\103.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-371***'],
    
    'AD ITEM NUMBER': ['127778'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'KEF300 Lakota Sport',
'KEF300 Lakota Utility'





]
#Range of years
years = list(range(1995, 2004))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\104.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-372***'],
    
    'AD ITEM NUMBER': ['122265'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'KVF750 Brute Force 4x4i',
'KVF750 Brute Force 4x4i EPS',
'KVF750 Brute Force 4x4i EPS Camo'



]
#Range of years
years = list(range(2005, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\105.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-379'],
    
    'AD ITEM NUMBER': ['122263'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'KVF750 Brute Force 4x4i',
'KVF750 Brute Force 4x4i EPS',
'KVF750 Brute Force 4x4i EPS Camo'



]
#Range of years
years = list(range(2003, 2024))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\106.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['103-376'],
    
    'AD ITEM NUMBER': ['122260'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'KFX450R'




]
#Range of years
years = list(range(2008, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\107.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-051'],
    
    'AD ITEM NUMBER': ['127782'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'LT250EF'





]
#Range of years
years = list(range(1984, 1987))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\108.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-051**'],
    
    'AD ITEM NUMBER': ['127782'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4'




]
#Range of years
years = list(range(1984, 1987))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\109.csv"
final_df.to_csv(file_path, index=False)

In [ ]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-057'],
    
    'AD ITEM NUMBER': ['122288'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'LT250R QuadRacer'





]
#Range of years
years = list(range(1987, 1993))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

In [ ]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\110.csv"
final_df.to_csv(file_path, index=False)

In [2]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-061'],
    
    'AD ITEM NUMBER': ['127732'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT300E'





]
#Range of years
years = list(range(1987, 1990))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT300E,NACH,NACHMAN INTERNATIONAL CO. LTD,104-061,127732,THUMB THROTTLE,1987
1,utv/atv,LT300E,NACH,NACHMAN INTERNATIONAL CO. LTD,104-061,127732,THUMB THROTTLE,1988
2,utv/atv,LT300E,NACH,NACHMAN INTERNATIONAL CO. LTD,104-061,127732,THUMB THROTTLE,1989

In [4]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\111.csv"
final_df.to_csv(file_path, index=False)

In [6]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-106'],
    
    'AD ITEM NUMBER': ['122282'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-4WD QuadRunner 250',
'LT-4WDX King Quad 250',
'LT230E QuadRunner'






]
#Range of years
years = list(range(1987, 1994))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1987
1,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1987
2,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1987
3,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1988
4,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1988
5,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1988
6,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1989
7,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1989
8,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1989
9,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1990
10,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1990
11,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1990
12,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1991
13,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1991
14,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1991
15,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1992
16,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1992
17,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1992
18,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1993
19,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1993
20,utv/atv,LT230E QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-106,122282,THUMB THROTTLE,1993

In [8]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\112.csv"
final_df.to_csv(file_path, index=False)

In [10]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-107'],
    
    'AD ITEM NUMBER': ['122287'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT250R QuadRacer'



]
#Range of years
years = list(range(1987, 1993))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1987
1,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1988
2,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1989
3,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1990
4,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1991
5,utv/atv,LT250R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-107,122287,THUMB THROTTLE,1992

In [12]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\113.csv"
final_df.to_csv(file_path, index=False)

In [14]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-103'],
    
    'AD ITEM NUMBER': ['127734'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT500R QuadRacer'



]
#Range of years
years = list(range(1987, 1991))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT500R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-103,127734,THUMB THROTTLE,1987
1,utv/atv,LT500R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-103,127734,THUMB THROTTLE,1988
2,utv/atv,LT500R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-103,127734,THUMB THROTTLE,1989
3,utv/atv,LT500R QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-103,127734,THUMB THROTTLE,1990

In [16]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\114.csv"
final_df.to_csv(file_path, index=False)

In [18]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-111'],
    
    'AD ITEM NUMBER': ['122247'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT80 QuadSport'



]
#Range of years
years = list(range(1987, 2007))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1987
1,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1988
2,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1989
3,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1990
4,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1991
5,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1992
6,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1993
7,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1994
8,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1995
9,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1996
10,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1997
11,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1998
12,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,1999
13,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2000
14,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2001
15,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2002
16,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2003
17,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2004
18,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2005
19,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-111,122247,THUMB THROTTLE,2006

In [20]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\115.csv"
final_df.to_csv(file_path, index=False)

In [22]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-110'],
    
    'AD ITEM NUMBER': ['127728'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT250EF',
'LT250S',
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4'



]
#Range of years
years = list(range(1987, 2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT250EF,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1987
1,utv/atv,LT250S,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1987
2,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1987
3,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1987
4,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1987
...,...,...,...,...,...,...,...,...
60,utv/atv,LT250EF,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1999
61,utv/atv,LT250S,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1999
62,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1999
63,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1999
64,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-110,127728,THUMB THROTTLE,1999

In [24]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\116.csv"
final_df.to_csv(file_path, index=False)

In [26]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-112'],
    
    'AD ITEM NUMBER': ['122284'],
    
    'Vendor Notes': ['CHOKE'],
}

#List of Models

list_models = [
    
'LT250EF',
'LT250S',
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4',
'LT-F300F KingQuad 4x4',
'LT-F230'



]
#Range of years
years = list(range(1987, 2001))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT250EF,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,1987
1,utv/atv,LT250S,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,1987
2,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,1987
3,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,1987
4,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,1987
...,...,...,...,...,...,...,...,...
93,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,2000
94,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,2000
95,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,2000
96,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,2000
97,utv/atv,LT-F230,NACH,NACHMAN INTERNATIONAL CO. LTD,104-112,122284,CHOKE,2000

In [28]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\117.csv"
final_df.to_csv(file_path, index=False)

In [30]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-118'],
    
    'AD ITEM NUMBER': ['122281'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-F160 QuadRunner'



]
#Range of years
years = list(range(1989, 2002))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1989
1,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1990
2,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1991
3,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1992
4,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1993
5,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1994
6,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1995
7,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1996
8,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1997
9,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1998
10,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,1999
11,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,2000
12,utv/atv,LT-F160 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-118,122281,THUMB THROTTLE,2001

In [32]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\118.csv"
final_df.to_csv(file_path, index=False)

In [34]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-119'],
    
    'AD ITEM NUMBER': ['122286'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-4WD QuadRunner 250',
'LT-4WDX King Quad 250',
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4',
'LT-F300F KingQuad 4x4'

]
#Range of years
years = list(range(1990, 2000))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
1,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
2,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
3,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
4,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
5,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1990
6,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
7,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
8,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
9,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
10,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
11,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1991
12,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
13,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
14,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
15,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
16,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
17,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1992
18,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
19,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
20,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
21,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
22,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
23,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1993
24,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
25,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
26,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
27,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
28,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
29,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1994
30,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
31,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
32,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
33,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
34,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
35,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1995
36,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
37,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
38,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
39,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
40,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
41,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1996
42,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
43,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
44,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
45,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
46,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
47,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1997
48,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
49,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
50,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
51,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
52,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
53,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1998
54,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999
55,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999
56,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999
57,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999
58,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999
59,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-119,122286,THUMB THROTTLE,1999

In [36]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\119.csv"
final_df.to_csv(file_path, index=False)

In [40]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-158'],
    
    'AD ITEM NUMBER': ['122285'],
    
    'Vendor Notes': ['REVERSE'],
}

#List of Models

list_models = [
    
'LT-4WD QuadRunner 250',
'LT-4WDX King Quad 250',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4'


]
#Range of years
years = list(range(1987, 1997))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1987
1,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1987
2,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1987
3,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1987
4,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1988
5,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1988
6,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1988
7,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1988
8,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1989
9,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1989
10,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1989
11,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1989
12,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1990
13,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1990
14,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1990
15,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1990
16,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1991
17,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1991
18,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1991
19,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1991
20,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1992
21,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1992
22,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1992
23,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1992
24,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1993
25,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1993
26,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1993
27,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1993
28,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1994
29,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1994
30,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1994
31,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1994
32,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1995
33,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1995
34,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1995
35,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1995
36,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1996
37,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1996
38,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1996
39,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-158,122285,REVERSE,1996

In [42]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\120.csv"
final_df.to_csv(file_path, index=False)

In [44]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-159**'],
    
    'AD ITEM NUMBER': ['122283'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'LT-4WD QuadRunner 250',
'LT-4WDX King Quad 250',
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4',
'LT-F300F KingQuad 4x4'


]
#Range of years
years = list(range(1987, 1997))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
1,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
2,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
3,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
4,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
5,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1987
6,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
7,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
8,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
9,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
10,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
11,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1988
12,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
13,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
14,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
15,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
16,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
17,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1989
18,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
19,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
20,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
21,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
22,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
23,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1990
24,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
25,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
26,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
27,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
28,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
29,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1991
30,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
31,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
32,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
33,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
34,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
35,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1992
36,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
37,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
38,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
39,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
40,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
41,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1993
42,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
43,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
44,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
45,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
46,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
47,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1994
48,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
49,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
50,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
51,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
52,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
53,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1995
54,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996
55,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996
56,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996
57,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996
58,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996
59,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-159**,122283,BRAKE,1996

In [46]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\121.csv"
final_df.to_csv(file_path, index=False)

In [48]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-188*'],
    
    'AD ITEM NUMBER': ['127774'],
    
    'Vendor Notes': ['BRAKE'],
}

#List of Models

list_models = [
    
'KFX80',
'LT80 QuadSport'

]
#Range of years
years = list(range(1987, 2007))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1987
1,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1987
2,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1988
3,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1988
4,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1989
5,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1989
6,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1990
7,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1990
8,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1991
9,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1991
10,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1992
11,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1992
12,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1993
13,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1993
14,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1994
15,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1994
16,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1995
17,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1995
18,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1996
19,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1996
20,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1997
21,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1997
22,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1998
23,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1998
24,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1999
25,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,1999
26,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2000
27,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2000
28,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2001
29,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2001
30,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2002
31,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2002
32,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2003
33,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2003
34,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2004
35,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2004
36,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2005
37,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2005
38,utv/atv,KFX80,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2006
39,utv/atv,LT80 QuadSport,NACH,NACHMAN INTERNATIONAL CO. LTD,104-188*,127774,BRAKE,2006

In [50]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\122.csv"
final_df.to_csv(file_path, index=False)

In [52]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-215'],
    
    'AD ITEM NUMBER': ['127729'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-4WD QuadRunner 250',
'LT-4WDX King Quad 250',
'LT-F250 Ozark',
'LT-F250 QuadRunner',
'LT-F250F QuadRunner 4x4',
'LT-F300F KingQuad 4x4'

]
#Range of years
years = list(range(1987, 2006))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-4WD QuadRunner 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,1987
1,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,1987
2,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,1987
3,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,1987
4,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,1987
...,...,...,...,...,...,...,...,...
109,utv/atv,LT-4WDX King Quad 250,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,2005
110,utv/atv,LT-F250 Ozark,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,2005
111,utv/atv,LT-F250 QuadRunner,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,2005
112,utv/atv,LT-F250F QuadRunner 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,2005
113,utv/atv,LT-F300F KingQuad 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-215,127729,THUMB THROTTLE,2005

In [54]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\123.csv"
final_df.to_csv(file_path, index=False)

In [56]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-228'],
    
    'AD ITEM NUMBER': ['122200'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'DVX 400',
'DVX 400 TS',
'KFX400',
'LT-A400 Eiger 2x4 Auto',
'LT-A400F Eiger 4x4 Auto',
'LT-A400F KingQuad AS',
'LT-A400F KingQuad ASi',
'LT-A400F KingQuad ASi LE',
'LT-A400F KingQuad ASi SE',
'LT-A400F KingQuad ASi+',
'LT-A400F KingQuad ASi SE+',
'LT-Z400 QuadSport Z',
'LT-Z400 QuadSport Z LE'

]
#Range of years
years = list(range(2003, 2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,DVX 400,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2003
1,utv/atv,DVX 400 TS,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2003
2,utv/atv,KFX400,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2003
3,utv/atv,LT-A400 Eiger 2x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2003
4,utv/atv,LT-A400F Eiger 4x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2003
...,...,...,...,...,...,...,...,...
86,utv/atv,LT-A400F KingQuad ASi SE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2009
87,utv/atv,LT-A400F KingQuad ASi+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2009
88,utv/atv,LT-A400F KingQuad ASi SE+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2009
89,utv/atv,LT-Z400 QuadSport Z,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2009
90,utv/atv,LT-Z400 QuadSport Z LE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-228,122200,THUMB THROTTLE,2009

In [58]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\124.csv"
final_df.to_csv(file_path, index=False)

In [60]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-229'],
    
    'AD ITEM NUMBER': ['127733'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-A400 Eiger 2x4 Auto',
'LT-A400F Eiger 4x4 Auto',
'LT-A400F KingQuad AS',
'LT-A400F KingQuad ASi',
'LT-A400F KingQuad ASi LE',
'LT-A400F KingQuad ASi SE',
'LT-A400F KingQuad ASi+',
'LT-A400F KingQuad ASi SE+'

]
#Range of years
years = list(range(2008, 2010))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-A400 Eiger 2x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
1,utv/atv,LT-A400F Eiger 4x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
2,utv/atv,LT-A400F KingQuad AS,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
3,utv/atv,LT-A400F KingQuad ASi,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
4,utv/atv,LT-A400F KingQuad ASi LE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
5,utv/atv,LT-A400F KingQuad ASi SE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
6,utv/atv,LT-A400F KingQuad ASi+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
7,utv/atv,LT-A400F KingQuad ASi SE+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2008
8,utv/atv,LT-A400 Eiger 2x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
9,utv/atv,LT-A400F Eiger 4x4 Auto,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
10,utv/atv,LT-A400F KingQuad AS,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
11,utv/atv,LT-A400F KingQuad ASi,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
12,utv/atv,LT-A400F KingQuad ASi LE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
13,utv/atv,LT-A400F KingQuad ASi SE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
14,utv/atv,LT-A400F KingQuad ASi+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009
15,utv/atv,LT-A400F KingQuad ASi SE+,NACH,NACHMAN INTERNATIONAL CO. LTD,104-229,127733,THUMB THROTTLE,2009

In [62]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\125.csv"
final_df.to_csv(file_path, index=False)

In [64]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-233'],
    
    'AD ITEM NUMBER': ['122295'],
    
    'Vendor Notes': ['THUMB THROTTLE'],
}

#List of Models

list_models = [
    
'LT-F500F Vinson 500 4x4'


]
#Range of years
years = list(range(2002, 2004))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,LT-F500F Vinson 500 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-233,122295,THUMB THROTTLE,2002
1,utv/atv,LT-F500F Vinson 500 4x4,NACH,NACHMAN INTERNATIONAL CO. LTD,104-233,122295,THUMB THROTTLE,2003

In [66]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\126.csv"
final_df.to_csv(file_path, index=False)

In [70]:
import pandas as pd

#init data
data1 = {
    'Make': ['utv/atv'],
    'Model': ['all models'],
    'Vendor Code': ['NACH'],
    'Vendor Name': ['NACHMAN INTERNATIONAL CO. LTD'],
    
    'MPN': ['104-232'],
    
    'AD ITEM NUMBER': ['122201'],
    
    'Vendor Notes': ['CLUTCH'],
}

#List of Models

list_models = [
    
'DVX 400',
'DVX 400 TS',
'KFX400',
'LT-Z400 QuadSport Z',
'LT-Z400 QuadSport Z LE',
'LT-R450 QuadRacer'



]
#Range of years
years = list(range(2002, 2015))

#Function to generate Dataframe for each model
def generate_df(model, data, year):
    data_copy = data.copy() # Creating a copy of data1 to avoid modifying the original dictionary
    data_copy['Model'] = model
    data_copy['Year'] = year
    return pd.DataFrame(data_copy)

# Generate DataFrames for all sets of data
dfs = []
for year in years:
    df1 = pd.concat([generate_df(model, data1, year) for model in list_models], ignore_index=True)
    dfs.append(df1)

# Concatenate all DataFrames
final_df = pd.concat(dfs, ignore_index=True)

# Print / Display
final_df

,Make,Model,Vendor Code,Vendor Name,MPN,AD ITEM NUMBER,Vendor Notes,Year
0,utv/atv,DVX 400,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2002
1,utv/atv,DVX 400 TS,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2002
2,utv/atv,KFX400,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2002
3,utv/atv,LT-Z400 QuadSport Z,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2002
4,utv/atv,LT-Z400 QuadSport Z LE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2002
...,...,...,...,...,...,...,...,...
73,utv/atv,DVX 400 TS,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2014
74,utv/atv,KFX400,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2014
75,utv/atv,LT-Z400 QuadSport Z,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2014
76,utv/atv,LT-Z400 QuadSport Z LE,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2014
77,utv/atv,LT-R450 QuadRacer,NACH,NACHMAN INTERNATIONAL CO. LTD,104-232,122201,CLUTCH,2014

In [72]:
file_path = r"C:\Users\User\Desktop\nachmann\2024 TASK\Section 05\04_Section 05 - Cables ( 11-01-23 )\Merge 2\127.csv"
final_df.to_csv(file_path, index=False)